### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by duke79** [carefortheliving/frontend#5]
* Fields
  * Title [disabled, must be auto generated]
    * THIS thing needed at THIS location
    * Field really needed though?
  * Image
  * Category [to be disabled if editing]
  * Description
  * State/District
  * Requestor's name
  * Contact number
  * Updated At
  * Different color scheme for Open/Close status
  * Status
    * To be shown only if editing
    * Two options
      * Open
      * Closed
* Submit button
  * OnClick redirects to `My Requests` Page

**Comment by alok722** [comment]
code has been pushed and deployed in previous commits
