### ISSUE TITLE
Link Card title overflowing

### ISSUE THREAD

**Issue by duke79** [carefortheliving/frontend#56]

**Comment by tanishghosh** [comment]
Hi !
Was trying to setup the project. On running the same using `npm run start`, I am getting an empty screen with the below console error:
![image](https://user-images.githubusercontent.com/38141788/115968115-c91e3200-a553-11eb-8adb-20df8c7f98a7.png)

Operating System : Windows 10 64-bit
Chrome Version : 90.0.4430.85

**Comment by alok722** [comment]
@tanishghosh I believe the firebase configuration is missing.
You need to create a .env file in the root folder and populate the value to the following keys:
```
SKIP_PREFLIGHT_CHECK=true
REACT_APP_FIREBASE_APIKEY=
REACT_APP_FIREBASE_AUTHDOMAIN=
REACT_APP_FIREBASE_PROJECTID=
REACT_APP_FIREBASE_STORAGEBUCKET=
REACT_APP_FIREBASE_MESSAGINGSENDERID=
REACT_APP_FIREBASE_APPID=
REACT_APP_FIREBASE_MEASUREMENTID=
```

you can get values to these fields by creating a Firebase project and configuring it for web app

**Comment by alok722** [comment]
issue resolved by @MiKr13
