### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by duke79** [carefortheliving/frontend#8]
* `Edit Icon` if request by the logged in user
* Title
* Image
* Category
  * Category specific fields
    * Plasma
      * Gender
      * Age
      * Blood Group
      * Hospital
* State/District
* Requestor's name
  * Show First Name only
  * Visible only if logged in
* Contact number
  * Visible only if logged in
* Updated At
* Different color scheme for Open/Close status
* Description

**Comment by alok722** [comment]
code has been pushed and deployed in previous commits
